# Generated by Django 3.2.9 on 2021-11-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_packages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='amount',
            new_name='hours',
        ),
    ]
